### ISSUE TITLE
"peerctl peer stat" fails: undefined local variable or method `a'

### ISSUE THREAD

**Issue by tora** [suzumura-ss/castoro#13]
<pre>
versions:
 castoro-peer-0.0.17 to 0.0.20

problem:
 $ peerctl peer stat
 undefined local variable or method `a' for #<Castoro::Peer::CpeerdWorkers::CpeerdTcpMaintenaceServer:0x82a7df8>

expectation:
 $ peerctl peer stat
 2010-12-17T14:02:02+09:00.119274 pr0 cpeerd.rb
   (ctp) Command receiver ticket pool             0
   (mtp) Multicast command sender ticket pool     0
   (rc ) Regular command receiver pipeline        0
   (ec ) Express command receiver pipeline        0
   (bs ) Basket status query database pipeline    0
   (sm ) Storage manupulator pipeline             0
   (ms ) Multicast command sender pipeline        0
   (tr ) TCP response sender pipeline             0
   (ur ) UDP response sender pipeline             0
   (re ) Replication request pipeline             0

causes:
    castoro-peer/lib/castoro-peer/cpeerd_workers.rb

        def do_stat
          ...
          while ( opt = a.shift )

    the variable 'a' should be '@a'
</pre>

**Comment by hamajyotan** [comment]
castoro-peer 0.0.17, 0.0.20 共に同事象が再現することを確認

<pre>
[dev@std101 ~]$ peerctl peer version std100 std101
2010-12-21T16:36:43+09:00.194716 std100 cpeerd Version: peer-0.0.20 - 2010-11-18
2010-12-21T16:36:44+09:00.072341 std101 cpeerd Version: peer-0.0.17 - 2010-09-21
[dev@std101 ~]$ peerctl peer stat std100 std101
undefined local variable or method `a' for #<Castoro::Peer::CpeerdWorkers::CpeerdTcpMaintenaceServer:0x909c474>
undefined local variable or method `a' for #<Castoro::Peer::CpeerdWorkers::CpeerdTcpMaintenaceServer:0x952d814>
[dev@std101 ~]$
</pre>

**Comment by hamajyotan** [comment]
castoro-peer 0.0.16 で同事象が再現することを確認

<pre>
[dev@std101 ~]$ peerctl peer version
2010-12-21T17:13:09+09:00.961138 std101 cpeerd Version: peer-0.0.16 - 2010-09-14
[dev@std101 ~]$ peerctl peer stat
undefined local variable or method `a' for #<Castoro::Peer::CpeerdWorkers::CpeerdTcpMaintenaceServer:0x99f6814>
[dev@std101 ~]$
</pre>

**Comment by hamajyotan** [comment]
castoro-peer 0.0.21 にて対応完了いたしました。

ToshiyukiTerashita/castoro@0fe421d837e8b5e6bffef4fc3e9f8caaf4b4fb41
