### ISSUE TITLE
ファイル read 可能な状態を保持したまま、グループを再構成したい 

### ISSUE THREAD

**Issue by hamajyotan** [suzumura-ss/castoro#16]
## 現状の問題点

peer グループを再構成する為に、デーモンの再起動が必要になる。
## 例
- peer01, peer02, peer03 でグループ化された状態で運用
- peer03 に異常発生。 (この時点で peer01-03 は全て読取専用 peer になる)
- 代替機である peer04 を準備、peer03 を外して、peer01, peer02, peer04 でグループを作成したい。
- しかし、それにはグループ再構成の為に peer01, peer02 の再起動が必要になる。
  - 再起動する場合、同グループが保持しているファイルは一時的に参照不可能になる。この状況を防ぎたい。
## 対応方式の候補
- 読取専用デーモンの常駐
- reload する

**Comment by hamajyotan** [comment]
## 指針
- 読取専用Peer を準備する
  - NOP, GET に対して応答する
  - watchdog を送信する
  - 現状の cpeerd, crepd, cmond とは別のプロセス

**Comment by hamajyotan** [comment]
## 読取専用Peer, castoro-peer コマンド

```
$ castoro-peer start --help
Usage: castoro-peer start [options]
    -v, --verbose                    verbose
    -d, --daemon                     daemon mode
    -p, --pid <pidfile>              PID file (only for the daemon mode)
    -l, --log <logfile>              Log file (only for the daemon mode)
    -c, --conf <configfile>          Config file
    -e, --env <environment>          Execution environment
```
- 機能
  - NOP, GET に対して応答する
  - (cmond からステータスを取得して) watchdog を送信する
  - (INSERT, DROP などの) 各種、UDP マルチキャストを行う

**Comment by tora** [comment]
2011年5月。検討の結果、三つの方式が考案されました。

<TABLE WIDTH=608 BORDER=1 BORDERCOLOR="#000000" CELLPADDING=4 CELLSPACING=0>
        <COL WIDTH=19>
        <COL WIDTH=167>
        <COL WIDTH=343>
        <COL WIDTH=44>
        <TR VALIGN=TOP>
            <TH WIDTH=19>
                <P><BR>
                </P>
            </TH>
            <TH WIDTH=167>
                <P>方式案</P>
            </TH>
            <TH WIDTH=343>
                <P>コメント</P>
            </TH>
            <TH WIDTH=44>
                <P>評価</P>
            </TH>
        </TR>
        <TR VALIGN=TOP>
            <TD WIDTH=19>
                <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">(a)</SPAN></FONT></P>
            </TD>
            <TD WIDTH=167>
                <P>遠隔制御コマンドで、設定ファイル<SPAN LANG="ja-JP">の</SPAN>再読込<SPAN LANG="ja-JP">を</SPAN>指示する</P>
                <P>例<FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">:
                xxx reload</SPAN></FONT></P>
            </TD>
            <TD WIDTH=343>
                <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">2010</SPAN></FONT><SPAN LANG="ja-JP">年初夏、開発工程で本機能の盛り込みを試みたが、グループ構成だけでなく、すべての設定項目の再読込を目指してしまったため、複雑になり過ぎ、先送りとなった。</SPAN></P>
                <P>グループ構成の変更だけに限るのであれば、比較的容易に実装可能。</P>
            </TD>
            <TD WIDTH=44>
                <P ALIGN=CENTER>実装</P>
                <P ALIGN=CENTER>次第</P>
            </TD>
        </TR>
        <TR VALIGN=TOP>
            <TD WIDTH=19>
                <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">(b)</SPAN></FONT></P>
            </TD>
            <TD WIDTH=167>
                <P>遠隔制御コマンドで、グループ構成の変更を指示する</P>
                <P>例<FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">:
                xxx group set mX mY m3</SPAN></FONT></P>
            </TD>
            <TD WIDTH=343>
                <P>設定ファイル内の記述内容と、運用上の設定が不一致になりかねない。運用上、問題となる。</P>
            </TD>
            <TD WIDTH=44>
                <P ALIGN=CENTER>悪</P>
            </TD>
        </TR>
        <TR VALIGN=TOP>
            <TD WIDTH=19>
                <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">(c)</SPAN></FONT></P>
            </TD>
            <TD WIDTH=167>
                <P>ピアの運用状態の放送を、別のデーモンにて行う</P>
            </TD>
            <TD WIDTH=343>
                <P>デーモンプロセスの数が増えるが、比較的容易に実装可能。</P>
                <P>運用上、直感的でわかり易い。</P>
            </TD>
            <TD WIDTH=44>
                <P ALIGN=CENTER>概ね</P>
                <P ALIGN=CENTER>良</P>
            </TD>
        </TR>
</TABLE>


案 (c)で、さらに検討を進めることになりました。

**Comment by tora** [comment]
2011年6月

<P>検討を進めるにつれ、マシン障害からの復旧手順を工夫すれば、現行のままで新規開発はせずに、十分対応できるのではないか、と考えるようになりました。</P>

<P>想定１：　３台中の１台に障害発生</P>

<TABLE WIDTH=100% BORDER=1 BORDERCOLOR="#000000" CELLPADDING=4 CELLSPACING=0>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <TR VALIGN=TOP>
                <TH WIDTH=17%>
                        <P>状態</P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m1</SPAN></FONT></P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m2</SPAN></FONT></P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m3</SPAN></FONT></P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mX</SPAN></FONT></P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mY</SPAN></FONT></P>
                </TH>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">1.
                        </SPAN></FONT>正常運転中</P>
                </TD>
                <TD WIDTH=17% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m1,
                        m2, m3</SPAN></FONT></P>
                </TD>
                <TD ROWSPAN=4 WIDTH=17% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m1,
                        m2, m3</SPAN></FONT></P>
                </TD>
                <TD ROWSPAN=3 WIDTH=17% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m1,
                        m2, m3</SPAN></FONT></P>
                </TD>
                <TD ROWSPAN=2 WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">-</SPAN></FONT></P>
                </TD>
                <TD ROWSPAN=6 WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">-</SPAN></FONT></P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17% BGCOLOR="#e6e6ff">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">2.
                        m1</SPAN></FONT><SPAN LANG="ja-JP">障害発生</SPAN></P>
                </TD>
                <TD ROWSPAN=5 WIDTH=17% BGCOLOR="#e6e6ff">
                        <P ALIGN=CENTER>（障害発生）</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">3.
                        mX</SPAN></FONT><SPAN LANG="ja-JP">稼動開始</SPAN></P>
                </TD>
                <TD ROWSPAN=4 WIDTH=17% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（稼動開始）</P>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mX,
                        m2, m3</SPAN></FONT></P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">4.
                        m3</SPAN></FONT>再構成</P>
                </TD>
                <TD ROWSPAN=3 WIDTH=17% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（停止、再起動）</P>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mX,
                        m2, m3</SPAN></FONT></P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">5.
                        m2</SPAN></FONT>再構成</P>
                </TD>
                <TD ROWSPAN=2 WIDTH=17% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（停止、再起動）</P>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mX,
                        m2, m3</SPAN></FONT></P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">6.
                        </SPAN></FONT>復旧完了</P>
                </TD>
        </TR>
</TABLE>

<P>
</P>

<P>想定２：　３台中の１台に障害発生し、読み取り専用で運用中、もう１台にも障害発生</P>

<TABLE WIDTH=100% BORDER=1 BORDERCOLOR="#000000" CELLPADDING=4 CELLSPACING=0>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <COL WIDTH=43*>
        <TR VALIGN=TOP>
                <TH WIDTH=17%>
                        <P>状態</P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m1</SPAN></FONT></P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m2</SPAN></FONT></P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m3</SPAN></FONT></P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mX</SPAN></FONT></P>
                </TH>
                <TH WIDTH=17%>
                        <P><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mY</SPAN></FONT></P>
                </TH>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">1.
                        </SPAN></FONT>正常運転中</P>
                </TD>
                <TD WIDTH=17% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m1,
                        m2, m3</SPAN></FONT></P>
                </TD>
                <TD ROWSPAN=2 WIDTH=17% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m1,
                        m2, m3</SPAN></FONT></P>
                </TD>
                <TD ROWSPAN=5 WIDTH=17% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">m1,
                        m2, m3</SPAN></FONT></P>
                </TD>
                <TD ROWSPAN=4 WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">-</SPAN></FONT></P>
                </TD>
                <TD ROWSPAN=3 WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">-</SPAN></FONT></P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17% BGCOLOR="#e6e6ff">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">2.
                        m1</SPAN></FONT><SPAN LANG="ja-JP">障害発生</SPAN></P>
                </TD>
                <TD ROWSPAN=6 WIDTH=17% BGCOLOR="#e6e6ff">
                        <P ALIGN=CENTER>（障害発生）</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17% BGCOLOR="#e6e6ff">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">3.
                        m2</SPAN></FONT>障害発生</P>
                </TD>
                <TD ROWSPAN=5 WIDTH=17% BGCOLOR="#e6e6ff">
                        <P ALIGN=CENTER>（障害発生）</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">4.
                        mY</SPAN></FONT><SPAN LANG="ja-JP">稼動開始</SPAN></P>
                </TD>
                <TD ROWSPAN=4 WIDTH=17% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（稼動開始）</P>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mX,
                        mY, m3</SPAN></FONT></P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">5.
                        mX</SPAN></FONT><SPAN LANG="ja-JP">稼動開始</SPAN></P>
                </TD>
                <TD ROWSPAN=3 WIDTH=17% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（稼動開始）</P>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mX,
                        mY, m3</SPAN></FONT></P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17%>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">6.
                        m3</SPAN></FONT><SPAN LANG="ja-JP">再構成</SPAN></P>
                </TD>
                <TD ROWSPAN=2 WIDTH=17% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（停止、再起動）</P>
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">mX,
                        mY, m3</SPAN></FONT></P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=17% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER><FONT FACE="Times New Roman, serif"><SPAN LANG="en-US">7.
                        </SPAN></FONT>復旧完了</P>
                </TD>
        </TR>
</TABLE>

<P>
</P>

<P>想定３：　１台の障害復旧作業中、もう１台にも障害発生</P>

<P>　→　想定１の復旧手順中に、想定２の復旧手順を併せた手順になると考えられます。</P>

<P>
</P>

<P>結局のところ、障害発生したマシンの台数に係わらず、その回復手順の基本的な考え方は同じであり、常に２台以上のマシンから読み取り可能としておけば、良いようです。</P>

<P>１．新たに投入した予備マシンを、新しいグループ構成にて稼動開始する。</P>

<P>　　　→　クライアント側は、そのマシンからも読み取りできるようになる。</P>

<P>２．古いグループ構成で稼動していた既存マシンを、新しいグループ構成で再起動する。</P>

<P>　　　→　再起動中に読み取りできない可能性があるが、他のマシンから読み取りできるので、問題ない。</P>

<P>このように、復旧手順の工夫により、今回の懸念事項は回避できると考えられます。</P>

**Comment by tora** [comment]
2011年7月

<P>読出停止させずにグループ再構成する方式を、先月に引き続き、検討いたしました。</P>

<P>その結果、保守者手順で解決できることがわかりました。</P>

<P></P>

<P STYLE="margin-left: 1.66cm; text-indent: -1.2cm; margin-bottom: 0cm">
<B>状況：</B>　３台マシン構成のピアグループにおいて、２台のマシンが停止した。残る１台で、クライアント側からの読み出しリクエストに応えている。</P>
<P STYLE="margin-left: 1.66cm; text-indent: -1.2cm; margin-bottom: 0cm; font-weight: normal">
</P>

<P STYLE="margin-left: 1.66cm; text-indent: -1.2cm; margin-bottom: 0cm">
<B>要求：</B>　残っている１台から予備マシンの２台へ、全コンテンツの全ファイルをコピーしたい。ただし、「コピーされたコンテンツを予備マシンが保持し始めた」ことを、ゲートウェイ内のキャッシュに反映させるため、コピーする手段として、レプリケーションを活用する。
</P>

<P STYLE="margin-left: 1.66cm; text-indent: -1.2cm; margin-bottom: 0cm">
<B>解決案：</B>　crepd
のみ、新しいグループ構成で、再起動する。
</P>

<P STYLE="margin-left: 1.66cm; text-indent: -1.2cm; margin-bottom: 0cm">
<B>補足：</B>　Castoro
では、障害発生時の復旧手順を容易にするために、どのコンテンツがどのピアマシンに保持されていかという情報を永続的には持ちません。そのお陰で、復旧作業は基本的に、データ用ディレクトリの内容を、そっくりそのまま、生きているマシンから予備マシンへコピーすればよいわけです。
</P><P>
とは言うものの、読み出し動作に要する時間を短縮するため、および、ピアマシンへ余計な負荷を掛けないようにするために、前面にゲートウェイマシンを配し、そのゲートウェイマシン内部のキャッシュ機構において、どのコンテンツがどれとどれとどのピアマシンに保持されているか、という情報を揮発的ですが保持するようにしてあります。
</P><P>
読み出しリクエストを受けると、まずこのキャッシュが参照され、目的のコンテンツを保持しているピアがヒットした場合には、そのピアから読み出しが行われます。一方、ミスヒットした場合には、全てのピアマシンへマルチキャストにて問い合わせが行われ、保持しているピアが応答し、読み出しが行われます。その際、同時に、それらのピアに関する情報がキャッシュに記録されます。
</P><P>
データ用ディレクトリを単にコピーした場合には、新しく組み込まれた予備マシンについてはまだキャッシュされていません。しかしながら、読み出しリクエストに対して残る１台がヒットするので、その予備マシンは読み出し対象となりません。よって、単にコピーした場合には、ゲートウェイ内部のキャッシュを一旦消去する必要があります。
</P><P>
コピーに代わる方法として、本件の要求条件のように、レプリケーション機構が活用できます。レプリケーションが行われると、レプリケーション先のピアがゲートウェイ内部のキャッシュへ自動的に記録されようになっているからです。</P>
<TABLE WIDTH=100% BORDER=1 BORDERCOLOR="#000000" CELLPADDING=4 CELLSPACING=0 STYLE="page-break-before: always">
        <COL WIDTH=51*>
        <COL WIDTH=32*>
        <COL WIDTH=32*>
        <COL WIDTH=66*>
        <COL WIDTH=37*>
        <COL WIDTH=37*>
        <TR VALIGN=TOP>
                <TH WIDTH=20%>
                        <P>状態</P>
                </TH>
                <TH WIDTH=13%>
                        <P>マシンm1</P>
                </TH>
                <TH WIDTH=13%>
                        <P>マシンm2</P>
                </TH>
                <TH WIDTH=26%>
                        <P>マシンm3</P>
                </TH>
                <TH WIDTH=15%>
                        <P>マシンmX</P>
                </TH>
                <TH WIDTH=15%>
                        <P>マシンmY</P>
                </TH>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>1.
                        正常運転</P>
                </TD>
                <TD WIDTH=13% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER>（状態30）</P>
                        <P ALIGN=CENTER>m1,
                        m2, m3</P>
                </TD>
                <TD WIDTH=13% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER>（状態30）</P>
                        <P ALIGN=CENTER>m1,
                        m2, m3</P>
                </TD>
                <TD WIDTH=26% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER>（状態30）</P>
                        <P ALIGN=CENTER>crepd
                        (30): m1, m2, m3</P>
                        <P ALIGN=CENTER>cpeerd
                        (30): m1, m2, m3</P>
                </TD>
                <TD ROWSPAN=4 WIDTH=15% BGCOLOR="#cccccc">
                        <P ALIGN=CENTER>-</P>
                </TD>
                <TD ROWSPAN=5 WIDTH=15% BGCOLOR="#cccccc">
                        <P ALIGN=CENTER>-</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>2.
                        m1に障害発生</P>
                </TD>
                <TD ROWSPAN=11 WIDTH=13% BGCOLOR="#cccccc">
                        <P ALIGN=CENTER>（障害発生）</P>
                </TD>
                <TD WIDTH=13% BGCOLOR="#ffcc99">
                        <P ALIGN=CENTER>（状態23）</P>
                </TD>
                <TD ROWSPAN=2 WIDTH=26% BGCOLOR="#ffcc99">
                        <P ALIGN=CENTER>（状態23）</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>3.
                        m2に障害発生</P>
                </TD>
                <TD ROWSPAN=10 WIDTH=13% BGCOLOR="#cccccc">
                        <P ALIGN=CENTER>（障害発生）</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>4.
                        読み出し専用へ</P>
                </TD>
                <TD ROWSPAN=3 WIDTH=26% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（状態20）</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>5.
                        mXを起動</P>
                </TD>
                <TD ROWSPAN=4 WIDTH=15% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（状態23）</P>
                        <P ALIGN=CENTER>mX,
                        mY, m3</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>6.
                        mYを起動</P>
                </TD>
                <TD ROWSPAN=3 WIDTH=15% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER STYLE="background: transparent">（状態23）</P>
                        <P ALIGN=CENTER>mX,
                        mY, m3</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>7.
                        m3を構成変更し</P>
                        <P ALIGN=LEFT>crepd
                        のみ再起動</P>
                </TD>
                <TD WIDTH=26% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（crepdのみ再起動）</P>
                        <P ALIGN=CENTER>crepd
                        (20): <U>mX, mY,</U> m3</P>
                        <P ALIGN=CENTER>cpeerd
                        (20): m1, m2, m3</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>8.
                        m3のcrepdを</P>
                        <P ALIGN=LEFT>レプリ可へ状態変更</P>
                </TD>
                <TD WIDTH=26% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（crepdのみ状態変更）</P>
                        <P ALIGN=CENTER>crepd
                        (<U>23</U>): mX, mY, m3</P>
                        <P ALIGN=CENTER>cpeerd
                        (20): m1, m2, m3</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>9.
                        レプリケーション</P>
                </TD>
                <TD WIDTH=26% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>mXへレプリ</P>
                </TD>
                <TD WIDTH=15% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>m3からレプリ</P>
                        <P ALIGN=CENTER>mYへレプリ</P>
                </TD>
                <TD WIDTH=15% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>
                        </P>
                        <P ALIGN=CENTER>mXからレプリ</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>10.
                        整合性チェック</P>
                </TD>
                <TD COLSPAN=3 WIDTH=55% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（整合性チェック）</P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>11.
                        m3のcpeerdを</P>
                        <P ALIGN=LEFT>新構成で再起動</P>
                </TD>
                <TD WIDTH=26% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>（cpeerdを再起動）</P>
                        <P ALIGN=CENTER>crepd
                        (23): mX, mY, m3</P>
                        <P ALIGN=CENTER>cpeerd
                        (20): mX, mY, m3</P>
                </TD>
                <TD WIDTH=15% BGCOLOR="#ccffff">
                        <P ALIGN=CENTER>
                        </P>
                </TD>
                <TD WIDTH=15% BGCOLOR="#ccffff">
                        <P>
                        </P>
                </TD>
        </TR>
        <TR VALIGN=TOP>
                <TD WIDTH=20%>
                        <P ALIGN=LEFT>12.
                        m3, mX, mYを</P>
                        <P ALIGN=LEFT>状態変更し</P>
                        <P ALIGN=LEFT>復旧完了</P>
                </TD>
                <TD WIDTH=26% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER>（状態30）</P>
                        <P ALIGN=CENTER>crepd
                        (30): mX, mY, m3</P>
                        <P ALIGN=CENTER>cpeerd
                        (30): mX, mY, m3</P>
                </TD>
                <TD WIDTH=15% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER>（状態30）</P>
                </TD>
                <TD WIDTH=15% BGCOLOR="#ffffcc">
                        <P ALIGN=CENTER>（状態30）</P>
                </TD>
        </TR>
</TABLE>
<P>
crepd: Castoro Replication Daemon;  cpeerd: Castoro Peer Daemon;  cmond: Castoro
Monitor Daemon</P>
<P>

</P>

<OL>
<LI>1.正常運転しています。　状態番号は「30:オンライン」です。</LI>
<LI>2.ピアマシンm1に障害が発生しました。</LI>
<LI>監視機構によって、状態番号が30から「23: 読み出し、および、レプリケーションは可、書き込みは不可」へ自動的に縮退しました。</LI>
<LI>3.ピアマシンm2に障害が発生しました。</LI>
<LI>4.保守者が手作業にて、m3の状態番号を23から「20: 読み出し専用」へ下げます。</LI>
<LI>5. 予備マシンmXを、新しいグループ構成（mX, mY, m3）で起動し、その状態番号を23へ上げます。</LI>
<LI>6. 予備マシンmXを、新しいグループ構成（mX, mY, m3）で起動し、その状態番号を23へ上げます。</LI>
<LI>7.m3の設定ファイルを編集して、グループ構成をm1,m2, m3 から mX, mY, m3 へ変更します。</LI>
<LI>その後、m3のcrepdを再起動して、変更内容をcrepdへ反映させます。</LI>
<LI>8. m3のcrepdの状態番号を20から23へ上げます。　これでレプリケーションが可能となります。</LI>
<LI>9.保守者が手作業で、m3の全コンテンツをmXへレプリケーションします。mXは、隣のmYへ自動的にレプリケーションします。</LI>
<LI>10.保守者が、各マシン（mX, mY, m3）間のコンテンツの整合性をチェックします。</LI>
<LI>11.m3のcmondおよび cpeerdを再起動し、手順7で編集した設定ファイルの内容を反映させます。</LI>
<LI>12.全マシン（mX, mY, m3）の状態番号を23 から「30: オンライン」へ上げ、復旧作業が完了します。</LI>
</OL>

<P STYLE="margin-left: 0.46cm"></P>

<P>上記のような保守者手順により、要求は満たされると考えられます。</P>

**Comment by tora** [comment]
クローズいたします。
