### ISSUE TITLE
castoro-manipulator によるディレクトリ作成時、パーミッションが正常に設定されない

### ISSUE THREAD

**Issue by ghost** [suzumura-ss/castoro#17]
## 現状の問題点

castoro-manipulator で作成されるディレクトリのパーミッションが umask の影響を受ける。
## 例
- peer からパーミッション「0777」のディレクトリ作成依頼を出す。
  - castoro-manipulator により作成されたディレクトリのパーミッションが「0755」となっている。
## 原因
- umask の設定の影響を受けている。
  - 結果、umask (0022) の場合、作成されたディレクトリのパーミッションは「0755」となる。
## 対応方法
- castoro-manipulator によるディレクトリの作成手順を以下に変更する。
  - 「mkdir + chown」 ⇒ 「mkdir  + chown + chmod」

**Comment by ghost** [comment]
## 修正内容
- castoro-manipulator/lib/castoro-manipulator/executor.rb
  - Castoro::Manipulator::Executor#mkdir 内
    - FileUtils#chmod による作成したディレクトリのパーミッションの変更を追加
    - Dir#mkdir の引数を「dir, mode」 ⇒ 「dir」に変更
    - FileUtils#chmod 時のエラー処理を追加
  - Castoro::Manipulator::Executor#make_parent_dir 内
    - FileUtils#chmod_R による再帰的に作成されたディレクトリのパーミッションの変更を追加
    - FileUtils#mkdir_p の引数を「dir, :mode => mode」 ⇒ 「dir」に変更

## 修正後のコード

castoro-manipulator/lib/castoro-manipulator/executer.rb
- Castoro::Manipulator::Executor#mkdir

<pre>
      def mkdir mode, user, group, dir
# 省略 ...
        # make directory.
        make_parent_dir(mode, user, group, File.dirname(dir)) {
          begin
            Dir.mkdir dir
            FileUtils.chmod mode, dir
            FileUtils.chown user, group, dir
          rescue
            FileUtils.remove_entry_secure dir
            raise
          end
        }
# 省略 ...
      end
</pre>

- Castoro::Manipulator::Executor#make_parant_dir

<pre>
      def make_parent_dir mode, user, group, dir
# 省略 ...
        FileUtils.mkdir_p dir
        FileUtils.chmod_R mode, nothing_dir if nothing_dir
        FileUtils.chown_R user, group, nothing_dir if nothing_dir
# 省略 ...
      end
</pre>


##

**Comment by ghost** [comment]
## 動作検証
- Rspec による動作検証
- manipulator へ直接パケットを送信して動作検証
  - 指定したパーミッションでディレクトリが作成されている事を確認する
  - 作成済みの上位ディレクトリのパーミッションが変更されない事を確認する
- 別ユーザの操作する castoro-client のスクリプトで動作検証
  - working ディレクトリのパーミッションを確認する
  - archive ディレクトリのパーミッションを確認する

**Comment by hamajyotan** [comment]
castoro-manipulator-0.1.1 で改修完了
ToshiyukiTerashita/castoro@71370b1af1460fd2b5bce099d11e741523fe54eb
