### ISSUE TITLE
ゲートウェイがステータス取得時に無応答になる

### ISSUE THREAD

**Issue by tora** [suzumura-ss/castoro#18]
# 不具合

ゲートウェイのステータス表示を試みると、数秒待たされ、エラーとなる。

バージョン番号: castoro-common-0.1.0, castoro-gateway-0.1.0

```
$ ruby -d /usr/local/bin/castoro-gateway status
/usr/local/lib/ruby/gems/1.9.1/gems/castoro-gateway-0.1.0/bin/castoro-gateway:76: warning: shadowing outer local variable - parser
/usr/local/lib/ruby/1.9.1/pathname.rb:270: warning: `*' interpreted as argument prefix
Using c extension for JSON.
/usr/local/lib/ruby/gems/1.9.1/gems/castoro-common-0.1.0/lib/castoro-common/receiver.rb:205: warning: shadowing outer local variable - port
/usr/local/lib/ruby/gems/1.9.1/gems/castoro-common-0.1.0/lib/castoro-common/workers_helper.rb:99: warning: useless use of :: in void context
/usr/local/lib/ruby/gems/1.9.1/gems/castoro-gateway-0.1.0/lib/castoro-gateway/scripts/script_runner.rb:178: warning: (...) interpreted as grouped expression
/usr/local/lib/ruby/gems/1.9.1/gems/castoro-common-0.1.0/lib/castoro-common/sender.rb:79: warning: instance variable @socket not initialized
Exception `Errno::EINPROGRESS' at /usr/local/lib/ruby/gems/1.9.1/gems/castoro-common-0.1.0/lib/castoro-common/sender.rb:162 - Operation now in progress - connect(2)
　　：
ここで数秒待って
　　：
Exception `NoMethodError' at /usr/local/lib/ruby/gems/1.9.1/gems/castoro-gateway-0.1.0/lib/castoro-gateway/scripts/script_runner.rb:139 - undefined method `keys' for nil:NilClass
--- Castoro::Gateway error! - undefined methoned met#
```

**Comment by tora** [comment]
# 再現性

条件が揃うと、必ず発生するようです。

<TABLE BORDER=1 BORDERCOLOR="#000000" CELLPADDING=4 CELLSPACING=0>
    <TR>
        <TD>
            <P ALIGN=CENTER><BR></P>
        </TD>   
        <TD>
            <P ALIGN=CENTER>MemTotal</P>
        </TD>
        <TD>
            <P ALIGN=CENTER>SwapTotal</P>
        </TD>
        <TD>
            <P ALIGN=CENTER>cache_size</P>
        </TD>
        <TD>
            <P ALIGN=CENTER>結果</P>
        </TD>
    </TR>
    <TR>
        <TD>
            <P ALIGN=CENTER>(a)</P>
        </TD>
        <TD>
            <P ALIGN=RIGHT>2097328 kB</P>
        </TD>
        <TD>
            <P ALIGN=RIGHT>0 kB</P>
        </TD>
        <TD>
            <P ALIGN=RIGHT>1500MB</P>
        </TD>
        <TD>
            <P ALIGN=CENTER>発生する</P>
        </TD>
    </TR>
    <TR>
        <TD>
            <P ALIGN=CENTER>(b)</P>
        </TD>
        <TD>
            <P ALIGN=RIGHT>2097328 kB</P>
        </TD>
        <TD>
            <P ALIGN=RIGHT>0 kB</P>
        </TD>
        <TD>
            <P ALIGN=RIGHT>256MB</P>
        </TD>
        <TD>
            <P ALIGN=CENTER>発生しない</P>
        </TD>
    </TR>
    <TR>
        <TD>
            <P ALIGN=CENTER>(c)</P>
        </TD>
        <TD>
            <P ALIGN=RIGHT>2097328 kB</P>
        </TD>
        <TD>
            <P ALIGN=RIGHT>2096472 kB</P>
        </TD>
        <TD>
            <P ALIGN=RIGHT>1500MB</P>
        </TD>
        <TD>
            <P ALIGN=CENTER>発生しない</P>
        </TD>
    </TR>
</TABLE>


grep Total /etc/meminfo などで、実装メモリ量、および、スワップ領域の容量を確認

<pre>
MemTotal:      2097328 kB
SwapTotal:           0 kB
</pre>


gateway.conf ファイル内のcache_sizeを確認

<pre>
cache_size: &lt;%= 1.5 * 1024 * 1024 * 1024  %&gt;
</pre>

**Comment by tora** [comment]
# 無応答になる理由

推測ですが、以下のような状況になっていると考えられます。
1. 運用中の castoro-gateway プロセスに対して外部からゲートウェイのstatus を得るために、外部から castoro-gateway プロセスへ TCP/IP 接続する。
2. castoro-gateway プロセス内部では select から戻ってきて、accept し、新しく作成されたソケットが割り当てられる。
3. Proc.newなどで、プロセスを fork しようと試みて、ENOMEM で失敗する。
4. Exception がキャッチされなかったため、そのスレッドは強制終了される。
5. その新しく作成されたソケットが close される前に、そのスレッドが強制終了されたため、外部から接続確立しているコネクションは開いたまま、無応答になる。
6. その外部からの接続を外部側で切る、もしくはその外部のプロセスを終了すると、FIN が飛び、castoro-gateway 側では、ESTABLISHED から CLOSE WAIT (netstat -an コマンドなどで確認) へ遷移し、FIN ACK を返さずに残る。
7. この時点で、スレッドが終了しているため、接続待ちのソケットを誰も select() していないという状況になる。
8. さらに、時間を遅らせて、再び外部から接続すると、listen() は起動時に行われているので、OS 側の TCP 層によって、新しい別の接続として ESTABLISHED まで状態は遷移するが、accept するスレッドがいないため、TCP層内のキューにつまれたまま、接続確立しているにも関わらず、無反応となる。
9. その外部からの接続を切断すると、TCP層のキューにつまれたままでacceptされるのを待っていた接続は、適切に切断される。

**Comment by tora** [comment]
# スレッドが終了しているのに、接続確立まで遷移してしまうのは、なぜ？

アプリケーション側で select() していないし、accept() するスレッドもいないのに、TCP層側で ESTABLISHED まで先に遷移してしまうのは、なぜでしょうか。

TCP/IP の接続確立時の 3-way-handshake による、(1) SYN を受信する、(2) SYN ACK を返す、(3) ACK を受信する。という処理において、アプリケーション側が関与してもよさそうなのですが、実装では、アプリケーション側は関与しないようになっているようです。

(1) SYN を受信した時点で、アプリケーション側にて発信元のIPアドレスおよびポート番号を見て、(a) 接続を許可する (SYN ACKを返す)、(b) 明示的に拒否する (RST を返す)、(c) 無視する (何も返答しない)、というような行動をとれそうなのですが、実際のところ、そのような役割分担については、ファイアーウォールが行えば良いわけですよね。

となると、届いた SYN に対してはすべて接続を許可すればよいわけです。そうであれば、アプリケーション側は、自分の処理内容に専念し、その処理中に次の接続要求が届いたら、アプリケーション側に手間を掛けさせずに、TCP層側にて、その次の接続要求についての 3-way-handshake を済ませておき、さらには、発信元から最初のデータを受信するところまで行っておくこともできますよね。

そうしておけば、アプリケーション側が自分の処理を終えて、TCP層側へ次の接続はありますか？と問い合わせたときには、接続確立が済んでいて、しかも最初のデータもすでに届いている。ということになり、効率が良いわけです。

このようなわけで、アプリケーション側でスレッドが終了していても、listen() されていれば、接続確立まで、さらには、最初のデータ受信まで、TCP層側にて行われるというわけです。

**Comment by tora** [comment]
# 仮対処

## 方法Ａ：　スワップ領域を拡張する

例：　スワップ領域を追加して、ENOMEM を回避する。

```
# mkdir -m 700 /swap
# dd if=/dev/zero of=/swap/swap0 bs=1M count=2048
# chmod 600 /swap/swap0
# mkswap /swap/swap0 2097152
# swapon /swap/swap0
```

さらに、 /etc/fstabに

```
 /swap/swap0        swap            swap    defaults    0 0
```

## 方法Ｂ：　ゲートウェイのキャッシュサイズを小さくする

gateway.conf ファイル内のcache_size 値を小さくして、ENOMEM を回避する。

**Comment by hamajyotan** [comment]
## (プログラムによる)対処

gateway の fork きっかけは現在 2パターン
- dump 要求受理時
- status 要求受理時

このうち後者は必ずしも fork が必要であるわけではない
0.1.0 で、上記の両方 fork が発生するのはロジック共有による実装都合。

改修指針
⇒ **余計な fork を防ぐため status 要求受理時には fork しないようにする。**

**Comment by hamajyotan** [comment]
castoro-gateway 0.1.1 で改修完了
- status コマンド受理時に、 fork しないようにする。
