### ISSUE TITLE
CLONEの実装

### ISSUE THREAD

**Issue by ghost** [suzumura-ss/castoro#2]
basketの内容を引き継いでbasketを更新したい。

**Comment by tora** [comment]
CLONE は、開発当初基本設計段階において候補に挙がった開発項目の一つでした。
ピア内部で、既存の basket を複製し、異なる basket として作成する機能として考えられました。

しかしながら、現在までのところ、CLONEの利用局面がありません。
よって、本issueを一旦クローズいたします。
