### ISSUE TITLE
timeslide_multicastのパフォーマンス改善

### ISSUE THREAD

**Issue by suzumura-ss** [suzumura-ss/castoro#20]
https://github.com/ToshiyukiTerashita/castoro/pull/19#commitcomment-412804
の対応。

**Comment by hamajyotan** [comment]
#21, #22 の改修がブランチ client-0.1.2 にコミット済
-> #20 の改修を含めて、 master にマージ予定

**Comment by hamajyotan** [comment]
## 確認 - TimeslideSender に渡す _destinations_ の値とその挙動

---

送信先の使用順序

@destinations に存在する値は、各セグメントから順番に送信先として使用される
- @destinations が [ [ "a", "b", "c", "d" ], [ "e", "f" ], [ "g", "h", "i" ] ] である場合
  - "a", "e", "g", "b", "f", "h", "c", "i", "d" の順序で送信される
- @destinations が [ [ "a", "b", "c" ] ] である場合
  - "a", "b", "c" の順序で送信される
- @destinations が [ [ "a", "b", "c", "d", "e" ], [ "f", "g" ] ] である場合
  - "a", "f", "b", "g", "c", "d", "e" の順序で送信される

---

送信先のサイクル

セグメントと、セグメントの中の要素をそれぞれサイクルする
- ⇒ [ [ "a", "b", "c", "d" ], [ "e", "f" ], [ "g", "h", "i" ] ]
- ⇒ [ [ "f", "e" ], [ "h", "i", "g" ], [ "b", "c", "d", "a" ] ]
- ⇒ [ [ "i", "g", "h" ], [ "c", "d", "a", "b" ], [ "e", "f" ] ]
- ⇒ [ [ "d", "a", "b", "c" ], [ "f", "e" ], [ "g", "h", "i" ] ]
- ⇒ [ [ "e", "f" ], [ "h", "i", "g" ], [ "a", "b", "c", "d" ] ]
- ⇒ ...

**Comment by hamajyotan** [comment]
## 改修指針

TimeslideSender のインスタンス生成時時に以下を実施しておく
- max_seg_size を計算する
- 事前に host, port = d.split(":") を計算しておく

**Comment by hamajyotan** [comment]
TimeslideSender の改修実施

#initialize

<pre>
-        @destinations.map! { |seg| seg = seg.sort_by{ rand } }
+        @destinations.map! { |seg|
+          seg.map { |d|
+            h, p = d.split(":")
+            { :host => h, :port => p }
+          }.sort_by { rand }
+        }
+        @blank_elements   = Array.new(@destinations.map { |d| d.size }.max)
</pre>


#timeslide_multicast

<pre>
-          max_seg_size = 0
-          @destinations.each do |seg|
-            max_seg_size = seg.size if seg.size > max_seg_size
-          end
-          
-          max_seg_size.times do |i|
-            @destinations.size.times do |j|
-              d = @destinations[j][i]
-              next if d.nil?
-              host, port = d.split(":")
-              @sender.send header, command, host, port
-            end
+          flat_destinations.each { |d|
+            @sender.send header, command, d[:host], d[:port]
             interval += @request_interval
             sleep interval
             break if Thread.current[:dying]
-          end
+          }
</pre>


#flat_destinations 実装

<pre>
+      ##
+      # Flat destinations is returned.
+      #
+      # === Example
+      #
+      # * [ ["a", "b", "c", "d"], ["e", "f"], ["g", "h", "i"] ]
+      #   => [ "a", "e", "g", "b", "f", "h", "c", "i", "d" ]
+      # * [ [ "A", "B", "C" ] ]
+      #   => [ "A", "B", "C" ]
+      # * [ [ 1, 2, 3, 4, 5], [6, 7] ]
+      #   => [ 1, 6, 2, 7, 3, 4, 5 ]
+      #
+      def flat_destinations
+        @blank_elements.zip(*@destinations).flatten.compact
+      end
</pre>

**Comment by hamajyotan** [comment]
ブランチ client-0.1.2 に push しました -> toshiyukiterashita/castoro@cfc21db14d9458542162a059bf54245b1d4d74f6
master にマージしました -> toshiyukiterashita/castoro@e077a347bf9ca250222d60cad6ab294997d34351

同時に castoro-client 0.1.2 をリリースしました。
