### ISSUE TITLE
castoro-clientのテストに失敗する

### ISSUE THREAD

**Issue by arukoh** [suzumura-ss/castoro#21]
# 実行環境
### ruby

``` shell
$ ruby -v
ruby 1.8.7 (2010-12-23 patchlevel 330) [i686-linux]
```
### gems

``` shell
$ gem list

*** LOCAL GEMS ***

castoro-common (0.1.0)
json (1.5.1)
rake (0.8.7)
rspec (1.3.2)
```
# 実行結果

``` shell
$ cd castoro-client
$ spec spec/client_public_method_spec.rb
（省略）
Castoro::Client when create the Response not intended.
- should raise Castoro::ClientError with TimeslideSender#send should be called once. (FAILED - 1)

Castoro::Client when create gateway connection failed.
- should raise Castoro::ClientError with #send should be called once. (FAILED - 2)
（省略）
1)
Spec::Mocks::MockExpectationError in 'Castoro::Client when create the Response not intended. should raise Castoro::ClientError with TimeslideSender#send should be called once.'
Mock Castoro::Client::TimeslideSender received :send with unexpected arguments
  expected: (#<Castoro::Protocol::Command::Get:0xb766a064 @basket=#<Castoro::BasketKey:0xb766a294 @revision=3, @content=1, @type=1>>)
       got: ([#<Castoro::Protocol::Command::Create:0xb7657cac @hints={"class"=>"hints", "length"=>0}, @basket=#<Castoro::BasketKey:0xb766b43c @revision=3, @content=1, @type=2>>])
./spec/client_public_method_spec.rb:186:

2)
Spec::Mocks::MockExpectationError in 'Castoro::Client when create gateway connection failed. should raise Castoro::ClientError with #send should be called once.'
Mock Castoro::Client::TimeslideSender received :send with unexpected arguments
  expected: (#<Castoro::Protocol::Command::Get:0xb764e7c4 @basket=#<Castoro::BasketKey:0xb764e828 @revision=3, @content=1, @type=1>>)
       got: ([#<Castoro::Protocol::Command::Create:0xb7643694 @hints={"class"=>"hints", "length"=>0}, @basket=#<Castoro::BasketKey:0xb764ec24 @revision=3, @content=1, @type=2>>])
./spec/client_public_method_spec.rb:197:

Finished in 0.058631 seconds

26 examples, 2 failures
```
# 補足

[L186](https://github.com/ToshiyukiTerashita/castoro/blob/master/castoro-client/spec/client_public_method_spec.rb#L186)、[L197](https://github.com/ToshiyukiTerashita/castoro/blob/master/castoro-client/spec/client_public_method_spec.rb#L197)を以下のようにすると成功します。
### 修正

``` ruby
...
@sender_mock.should_receive(:send).once.with(@create_command).and_return {
...
```

**Comment by hamajyotan** [comment]
該当箇所を下記に改修して、 rspec 1.3.1, rspec 1.3.2 両バージョンで動作する事を確認しました。

client_public_method_spec.rb

<pre><code>
@@ -183,7 +183,7 @@ describe Castoro::Client do
 
     context "the Response not intended." do
       it "should raise Castoro::ClientError with TimeslideSender#send should be called once." do
-        @sender_mock.should_receive(:send).once.and_return {
+        @sender_mock.should_receive(:send).once.with(@create_command).and_return {
           Castoro::Protocol::Response::Create.new nil, @key
         }
         Proc.new {
@@ -194,7 +194,7 @@ describe Castoro::Client do
 
     context "gateway connection failed." do
       it "should raise Castoro::ClientError with #send should be called once." do
-        @sender_mock.should_receive(:send).once.and_return {
+        @sender_mock.should_receive(:send).once.with(@create_command).and_return {
           Castoro::Protocol::Response::Create::Gateway.new "error", @key, {}
         }
         Proc.new {
@@ -229,8 +229,6 @@ describe Castoro::Client do
         Proc.new {
           @client.create_direct(@peers, @key, @hints) {}
         }.should raise_error(Castoro::ClientNothingPeerError)
-
-
       end
     end
   end
</code></pre>

**Comment by hamajyotan** [comment]
## ブランチ client-0.1.2 にコミット完了

toshiyukiterashita/castoro@2d918dbd4b0fd1e25405a142840ea80d95524f47
- rspec 1.3.1, 1.3.2 での正常動作を確認済

#20 が完了次第 master にマージする
