### ISSUE TITLE
castoro-clientのテストに重複がある

### ISSUE THREAD

**Issue by arukoh** [suzumura-ss/castoro#22]
# 重複
- [client_public_method_spec.rb#L175](https://github.com/ToshiyukiTerashita/castoro/blob/master/castoro-client/spec/client_public_method_spec.rb#L175)
- [client_public_method_spec.rb#L217](https://github.com/ToshiyukiTerashita/castoro/blob/master/castoro-client/spec/client_public_method_spec.rb#L217)

L175のテストは、@client.create_direct()でなく@client.create()の評価を実施すべきかと思われます。

**Comment by hamajyotan** [comment]
## 確認しました、ご指摘の通りでした。
- [client_public_method_spec.rb#L175](https://github.com/ToshiyukiTerashita/castoro/blob/master/castoro-client/spec/client_public_method_spec.rb#L175)

上記については、 @client.create() の評価を実施すべきでした。

**Comment by hamajyotan** [comment]
該当箇所を下記に改修して、 rspec 1.3.1, rspec 1.3.2 両バージョンで動作する事を確認しました。

client_public_method_spec.rb

<pre><code>
     context "if connet peers failed" do
       it "should raise ClientNothingPeerError." do
+        @sender_mock.should_receive(:send).once.with(@create_command).and_return {
+          Castoro::Protocol::Response::Create::Gateway.new nil, @key, @peers
+        }
         @client.should_receive(:connect).once.and_return(false)
         Proc.new {
-          @client.create_direct(@peers, @key, @hints) {}
+          @client.create(@key, @hints) {}
         }.should raise_error(Castoro::ClientNothingPeerError)
       end
     end
</code></pre>

**Comment by hamajyotan** [comment]
## ブランチ client-0.1.2 にコミット完了

toshiyukiterashita/castoro@2d918dbd4b0fd1e25405a142840ea80d95524f47
- rspec 1.3.1, 1.3.2 での正常動作を確認済

#20 が完了次第 master にマージする
