### ISSUE TITLE
開発団体名を決めましょう→ "Castoro project" に決定

### ISSUE THREAD

**Issue by suzumura-ss** [suzumura-ss/castoro#24]
コードにある "Ricoh" を消す方向です。

案としては：
- Castoro project / Castoroプロジェクト
- Castoro Development Commission / Castoro開発委員会

**Comment by hamajyotan** [comment]
Castoro project / Castoroプロジェクト
に、一票です。

**Comment by suzumura-ss** [comment]
Castoro project
が短くていいなぁ。

**Comment by suzumura-ss** [comment]
"Castoro project" に決定しました。
