### ISSUE TITLE
Castoro-Gateway ドキュメント作成

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#30]
# Gatewayのドキュメントを作成する。

概要
- castoro-gateway は分散ファイルストレージシステム「castoro」にキャッシュ機能を提供しているコンポーネントである。
- 主な役割はストレージの窓口となる事である。
- ⇒ 目的はストレージ内の basket 探索回数を減らす事。
# TODO

　　　ドキュメントを提出する

**Comment by hamajyotan** [comment]
## 完了

https://www.quanp.net/contents/41753333
