### ISSUE TITLE
Castoro-Manipulator ドキュメント作成

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#34]
# Manipulatorのドキュメントを作成する。

概要
- Castoro システムでは castoro-peer のサブコンポーネントとして機能しており、ディレクトリの作成・移動を担っている
  - リクエストに応じてディレクトリを作成・移動する
  - 通信方式は UNIX ソケット通信である
# TODO

　　　ドキュメントを提出する

**Comment by hamajyotan** [comment]
ドキュメント作成完了
