### ISSUE TITLE
Kyotocabinetとの依存関係について検討する

### ISSUE THREAD

**Issue by hamajyotan** [suzumura-ss/castoro#35]
Kyotocabinet 版 Gateway を実装する場合に、依存 gem である kyotocabinet-ruby との依存関係を gem ファイルに定義すべきか否か

<pre>
spec.add_dependency 'kyotocabinet-ruby'
</pre>

## 問題点

gem の依存関係を定義してしまうと、
kyotocabinet を使わない場合であっても、 gem kyotocabinet-ruby との依存関係があるために
インストールが必要になってしまう。
## kyotocabinet-ruby のインストール

> kyotocabinet が必要 > gcc 4.4 が必要
## DONE 条件

上記問題に対する落とし所をつける

**Comment by suzumura-ss** [comment]
含めるべきではないと考えます。
例えば、Rails+MySQLで使うケースは多々ありますが、ruby-mysql は Rails の依存gemにはないですよね。

**Comment by hamajyotan** [comment]
## 新しい gem castoro-gateway-kyotocabinet を作成する
- 現状の castoro-gateway は依存関係そのまま（kyotocabinet-ruby に依存しない）
- gem kyotocabinet-ruby に依存する
- KyotoCabinet ベースの Gateway キャッシュクラス
- castoro-gateway 組み込みの Castoro::Cache とほぼ同様の I/F を有するクラス Castoro::Cache::KyotoCabinet を定義する

## Gateway のコンフィグに新しい値を定義する

<pre>
gateway.conf
  require: ["kyotocabinet"]
  cache:
    class: KyotoCabinet
</pre>

- require:
  - gateway プロセス開始直後に require する名称を配列で記述
- cache/class:
  - (代替)キャッシュクラスの名称を与える、後述の I/F を有する必要がある。
  - Castoro::Cache:: 以降の文字列。例えば、 Castoro::Cache::KyotoCabinet クラスの場合は "KyotoCabinet"

## Castoro::BasketCache#initialize でのキャッシュクラス初期化コード

<pre>
klass = Castoro::Cache
klass = Castoro::Cache.const_get(config['class'].to_s) if config['class']
cache = klass.new page
</pre>

**Comment by suzumura-ss** [comment]
cache:class: Hash が使えると最小構築するのに便利かもしれないですね。

**Comment by hamajyotan** [comment]
@14a0ce9cd69be9d1126d2751edc9c8557fc5f8ad

上記コミットにより、キャッシュの実体を別クラスに変更可能にした。
コンフィグ例

<pre>
default:
  require: ["castoro-gateway-hash"]
  cache:
    class: Hash
</pre>


上記設定により、代替キャッシュとして Castoro::Cache::Hash を使用可能になる

kyotocabinet 版キャッシュ適用例

<pre>
default:
  require: ["castoro-gateway-kyotocabinet"]
  cache:
    class: KyotoCabinet
</pre>

**Comment by hamajyotan** [comment]
## BasketCache クラスが使う、現在の Cache クラスの I/F

Cache クラス
- initialize page
  - 初期化
- watchdog_limit
  - WatchdogLimit を取得する
- watchdog_limit= value
  - WatchdogLimit を設定する
- peers
  - Peers クラスのインタンスを返す
- find content, type, revision
  - 要素の検索。見つかったNFSパスの配列を返す。
- stat key
  - Cache の統計情報を返す
- dump io
  - Cache の内容をダンプする

Peers クラス
- [] key
  - Peer クラスのインスタンスを返す
- find require_spaces
  - ACTIVE、かつ:availableがrequire_spaces以上のPeerの配列を返す

Peer クラス
- insert content, type, revision, base_path
  - 要素の追加。追加された要素数を返す
- erase content, type, revision
  - 要素の削除。削除された要素数を返す
- status
  - Peerステータスを返す
- status= val
  - Peerステータスを設定する

**Comment by hamajyotan** [comment]
## Cache クラスに、配下クラスを用いるメソッドのエイリアスを定義する。

以下、 Ruby のイメージ

<pre>
class Cache
  def find_peers(require_spaces)
    self.peers.find(require_spaces)
  end
  def insert_element(peer, content_id, content_type, revision, base_path)
    self.peers[peer].insert(content_id, content_type, revision, base_path)
  end
  def erase_element(peer, content_id, content_type, revision)
    self.peers[peer].erase(content_id, content_type, revision)
  end
  def get_peer_status(peer)
    self.peers[peer].status
  end
  def set_peer_status(peer, hash)
    self.peers[peer].status = hash
  end
end
</pre>

**Comment by hamajyotan** [comment]
## 既存メソッドの変更
- #initialize の引数変更
- watchdog_limit への writer は廃止

<pre>
class Cache
  def initialize cache_size, options = {}
    # 実装省略
  end
end
</pre>


BasketCache クラスでの初期化手順
- コンフィグ値 cache/options に設定されたハッシュ値を options に設定する
- 唯一の Logger インスタンスを options[:logger] に設定する
- コンフィグ値 cache/watchdog_limit が存在する場合 options[:watchdog_limit] に設定する （後方互換）

例

<pre>
default:
  cache:
    watchdog_limit: 12
    options:
      foo: bar
</pre>


上記のようなコンフィグがあった場合、初期化パラメータは以下のようになる

<pre>
  options = {
    :logger => @logger,
    :watchdog_limit => 12,
    :foo => "bar",
  }
  @cache = Cache.new cache_size, options
</pre>

**Comment by hamajyotan** [comment]
Castoro Cache プラグイン仕様

https://github.com/ToshiyukiTerashita/castoro/wiki/Castoro%3A%3Acache-plugin-specifications
