### ISSUE TITLE
Castoroドキュメント改訂

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#36]
# 指摘事項は3点
1. 5.2.x章
   - gatewayコマンドの「dump」を追記
2. 6.3.1章
   - クラス図に、C拡張ライブラリのクラスを追記
3. 同上
   - C拡張ライブラリで実現している機能に関して、データ構造や管理の概要について追記

**Comment by lamatsujun** [comment]
タスク状況　2011/12/02
1. 内容追記済み
2. クラス図作成中
   - Ruby側のクラス図 ：　レビュー終了
   - C++製キャッシュ内部のクラス図　：レビー中
3. ドラフト版作成中　：　レビュー中

**Comment by hamajyotan** [comment]
ドキュメント作成完了

https://www.quanp.net/contents/42616466
