### ISSUE TITLE
FINALIZE時にcsmが中間ディレクトリの作成に失敗する？

### ISSUE THREAD

**Issue by suzumura-ss** [suzumura-ss/castoro#4]
/usr/local/lib/ruby/gems/1.8/gems/castoro-client-0.0.9/lib/castoro-client/client.rb:343:in `create_internal': finalize command failed - #<Castoro::Protocol::Response::Finalize:0xb7dc4b0c @error={"message"=>"Castoro::ManipulatorError, directory already exist - /expdsk/1/baskets/a/0/016/752", "code"=>"Castoro::Peer::CommandExecutionError"}>, std104. (Castoro::ClientError)

[std104]$ grep 016/752 /var/adm/messages
Oct 28 16:49:12 std104 cpeerd[6308]: [ID 702911 daemon.warning] CSM Error: Castoro::ManipulatorError, directory already exist - /expdsk/1/baskets/a/0/016/752

**Comment by tora** [comment]
ディレクトリの作成作業においては、作成対象ディレクトリの存在確認のif文(1行目)から、
実際にmkdirする行(2行目)までの間に、自スレッドがプリエンプションされて他のスレッドが
動作して、もしくは、他のプロセスが動作して、その間に、作成対象のディレクトリが別の
スレッドもしくはプロセスによって作成される、という可能性がありますので、少なくとも、
mkdirの結果に対して、エラーであった場合、「既に存在している」エラーだったのかどうかを
判定する配慮が必要であると思います。

配慮がなされていない例

<pre>
 1  if ( dir は存在していない？ )
 2    error = mkdir( dir )
 3    if ( error が発生した？ )
 4      例外送出
 5    end
 6  else
 7    例外送出、もしくは、何もしない
 8  end
</pre>


改善例

<pre>
 1  if ( dir は存在していない？ )
 2    error = mkdir( dir )
 3    if ( error が発生した？ )
 4      if ( error の内容は「既に存在している」？ )
 5        正常終了
 6      else
 7        例外送出
 8      end
 9    end
10  else
11    例外送出、もしくは、何もしない
12  end
</pre>


上記の作業をRubyで実装した場合は、C, C++言語などで実装した場合に比べて、行間で
プリエンプションされる可能性がより高いですから、要注意かと思います。

**Comment by tora** [comment]
二つ以上の似通ったバスケットID、例えば、016752000 と 016752001 などに対して、
ほぼ同時に FINALIZE が行われたのではないかと、推測いたします。
その結果、/expdsk/1/baskets/a/0/016/752 ディレクトリの作成が、ほぼ同時に
複数行われ、片方については正常終了し、もう一方についてはエラーとなってしまったの
ではないかと、考えられます。

<pre>
ggrep -B20 -A20 016/752 /var/adm/messages
</pre>

などで、ログの内容について、エラーが記録された行の前後20行程度、差し支えなければ、
お教えいただけませんでしょうか。

**Comment by hamajyotan** [comment]
<pre>
  if ( dir は存在していない？ )
    error = mkdir( dir )
    if ( error が発生した？ )
      if ( error の内容は「既に存在している」？ )
        正常終了
      else
        例外送出
      end
    end
  else
    例外送出、もしくは、何もしない
  end
</pre>


FileUtils.mkdir_p は上記手順を踏襲した実装になっている。
Castoro::Manipulator で実装されている mkdir を 
FileUtils.mkdir_p で実装するように変更する。

**Comment by hamajyotan** [comment]
castoro-manipulator 0.0.8 と称して上記改修に至りました。
※ FileUtils.mkdir_p

⇒ 現在レビュー中、完了次第 push 予定。

**Comment by tora** [comment]
FileUtils.mkdir_p は上記手順を踏襲した実装になっていない。
FileUtils.mkdir_p は、

　ディレクトリの存在有無を確認せずに、とにかく mkdir してしまう。そして、
　その結果、エラーが発生しなければ、よしとし、
　　　　　　エラーが発生したとしても、ディレクトリが存在していたら、よしとする。
　　　　　　エラーが発生し、ディレクトリが存在していなければ、例外とする。

というような、
　1. まったくもって不要な mkdir を大量に発行する。
　2. エラーの種別をまったく調べていないし、報告もしない。
　3. umask 値と連携していない。

さらに、Castoro における要求仕様として、

　4. 中間ではなく、最終的なディレクトリを作成しようとした時点において、
　　　mkdir してエラーとなり、ディレクトリが存在していたら、、、
　　　「よし」ではなく、「エラー」でなければならないが、考慮されていない。
　　　よって、 mkdir_p フルパス名　というような使い方は、してはならない。

　5. 設定ファイルで指定されているベースとなるディレクトリ /expdsk が
　　　存在していない場合、mkdir してはならない。
　　　mkdir_p を単純につかってしまうと、データ用ディスクではなく、
　　　起動用ディスクにデータ用ディレクトリが作成されてしまう。

　6. FileUtils の仕上がり具合は、Castoro に使うには、未熟ではないかと
　　　感じられます。

などなど、FileUtils.mkdir_p は Castoro の生命線であるデータ用ディレクトリ
を扱わせるには、多くの問題があります。

Castoro においては複数のトランザクションが並行して動作するという性質を踏まえ、
CREATE が２発同時に飛んできた。
CREATE による mkdir 系と CANCEL, DELETE, FINALIZE などによる mv 系が
同時に飛んできた。
Ruby のスクリプトは、各行毎に停止し、他のスレッドに切り替わる確立が高い。
Ruby の実装上、および、UNIX の実装上、I/O 関連のシステムコール mkdir や
rename, ファイル存在有無確認の stat などを発行するような Ruby のコードを実行
すると、他のプロセスや同一プロセス内の他のスレッドへ実行が切り替わる可能性が高い。

上述の参考コードについても、十分だとは言えないと考えております。

はっきり言わせてもらって、FileUtils.mkdir_p ではなく、Castoro の要求仕様
および品質を満たすコードを、しっかりと腰をすえて、開発するべきではないかと考えます。

**Comment by tora** [comment]
問題となった現象のおさらい

<pre>
123456000 から 123456999 が存在していない状において、
123456000.0.1 の FINALIZE 
123456111.0.1 の FINALIZE 
の二つがほぼ同に一つのピアに到着すると、FINALIZE 処理であります
mv /expdsk/0/w/... /expdsk/0/a/0/123/456/123456000.0.1
mv /expdsk/0/w/... /expdsk/0/a/0/123/456/123456111.0.1
が行われるわけですが、この時点において、
/expdsk/0/a/0/123/456 がまだ存在していないわけですから、mv の前に
mkdir /expdsk/0/a/0/123/456
mkdir /expdsk/0/a/0/123/456
が二発発行され、先に行された方は正常終了し、
後に実行された方はエラーとなり、FINALIZE がエラーとなってしまう。
</pre>

**Comment by tora** [comment]
チャットにて議論した結果、以下の方向で行くこととなりました。

<pre>
作成対象のパス名を二つの部分へ分解する　⇒　/中間のパス/末尾
そして、それぞれに対して、
中間　⇒　FileUtils.mkdir_p
末尾　⇒　Dir.mkdir
</pre>

**Comment by hamajyotan** [comment]
castoro-manipulator 0.0.8 で対応完了

ToshiyukiTerashita/castoro@222d399e23eec012d581920f8f4c47415919f971
