### ISSUE TITLE
watchdog 送出機能を実装する

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#41]
# 現状の問題点・修正点
- Gateway から　Master Gateway への Watchdog 送出機能がない。
# 対応内容
- Gateway が Peer から受け取る Watchdog のように、Master Gateway へ Watchdog を送出可能する。
- 送信間隔は3分程度（1～5分の乱数などで散らばるように）

**Comment by hamajyotan** [comment]
ISLAND コマンド

ISLAND の統計情報を通知するためのコマンド
- island
  - 島ID
- Storables
  - Basket保存可能Peer数
- Capacity
  - Basket保存可能Peerの空き容量合計

**Comment by hamajyotan** [comment]
Gateway は定期的に ISLAND コマンドを送出可能とする
MGW は、ISLAND コマンドを受信して島の統計情報を保持する。
