### ISSUE TITLE
CREATE / GET レスポンスに ISLAND を追加する

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#42]
# マルチセグメント化に対し、現状では対応できない点
- レスポンスに ISLAND が存在しないため、現在のコンテンツがどの ISLAND に格納されるかが把握できない
# 対応内容
- GW からレスポンスする際に、 ISLAND を追加する。

**Comment by hamajyotan** [comment]
対象レスポンス
- CREATE
- GET

それぞれに island を付与する
