### ISSUE TITLE
コンフィグレーションにより GW / MGW を判別可能にする

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#44]
# 現状の問題点・修正点
- 今の Gateway には Master Gateway の機能がない。
- Gateway か Master Gateway かをどのように判別するのか。
# 対応内容
- Gateway か Master Gateway をコンフィグ上の設定で切り替えできるようにする。
- コンフィグ値そのものの検討が必要。

**Comment by hamajyotan** [comment]
gateway の config 値追加
- master
  - 自身が MGW であるならば true そうでないならば false
- master_multicast_addr
  - 自身が MGW でない場合の、 MGW のマルチキャストアドレス
- island_multicast_addr
  - 自身が MGW でない場合の、 島のマルチキャストアドレス
- island_multicast_device_addr
  - 自身が MGW でない場合の、 GW 間のマルチキャストデバイスのアドレス
