### ISSUE TITLE
MGW が GW の ISLAND を保持する。

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#48]
# マルチセグメント化に対し、現状では対応できない点
- Gateway を ISLAND で管理していない為、ISLAND の管理方法を実装する必要がある。
# 対応内容
- Master Gateway が Gateway からの watchdog を受け取る。
- watchdog の内容から ISLAND と Gateway との対応を保持する。

**Comment by lamatsujun** [comment]
- 要検討
  - ISLAND ⇒ マルチキャストアドレスの対応
  - ISLAND ＝ マルチキャストアドレスでも良い
- **決定事項**
  -  ISLAND = マルチキャストアドレス　で対応させる。

**Comment by hamajyotan** [comment]
- ISLAND コマンドの受信
- 島の統計情報の保存
