### ISSUE TITLE
MGW が CREATE を受信し、GW へパケットを中継する

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#49]
# マルチセグメント化に対し、現状では対応できない点
- CREATE を受信した際の挙動は、Peer の紹介である。
# 対応内容
- Master Gateway が CREATE を受け取ったときは、Gateway への中継する。

**Comment by lamatsujun** [comment]
ISLAND 統計情報から CREATE コマンドリレー順序を決める
CREATE コマンドをリレーする
- 懸念
  - 「別 ISLAND ならば作成できたかもしれない」というパターンのサルベージが必要
  - CREATE を受け、作成可能 Peer が無い場合、GW がレスポンスをしてはダメかもしれない。
- **決定事項**
  - **MGW は CREATE 受信の際、選定した 特定の ISLAND にマルチキャストする。**

**Comment by hamajyotan** [comment]
CREATE リレー先の島は 1つ。
- 自身が持つ、統計情報からリレー先の島を決定する
- CREATE コマンドを該当島へリレーする
