### ISSUE TITLE
castoro-common に type id 別 パス生成機能を追加する

### ISSUE THREAD

**Issue by tora** [suzumura-ss/castoro#56]
ピア内部では、basket id に対応したパスを生成し、同パス名のディレクトリ内にパスケットを保管している。
同パス名は、GW でも生成され、GWがクライアント側へ紹介している。
すなわち、ピアと GW の2カ所で同じパス名を生成していることになる。
よって、それらのコードの共通化を図り、castoro-common 内へ配置する。

加えて、10進数指向のパス名、および、16進数指向のパス名を type id 値に応じて切り替えて作成できるようにする。

**Comment by hamajyotan** [comment]
Castoro::BasketKeyConverter 作成完了

gateway, peer でそれぞれ同を用いてパス導出するように変更完了

**Comment by hamajyotan** [comment]
0.2.0 リリースに伴いクローズ

同クラスは castoro-common 0.2.0 に内包
