### ISSUE TITLE
BasketKeyConverter を組み込む

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#57]
## TODO
- [basket_key_converter](https://github.com/ToshiyukiTerashita/castoro/blob/0.2/castoro-common/lib/castoro-common/basket_key_converter.rb)
- Gateway のキャッシュから BasketkeyConverter を用いて、パスを導出する。
- キャッシュへのべ―スパス格納部を除去する。

**Comment by suzumura-ss** [comment]
Castoro::Cache#make_nfs_path はオーバーライド可能ですので、そこから実装するほうが簡単かもしれません。
https://github.com/ToshiyukiTerashita/castoro/blob/master/castoro-gateway/ext/cache.cxx#L34

**Comment by hamajyotan** [comment]
ご提言有難うございます。
make_nfs_path の再定義も検討しましたが
パス導出機構の外部化により、
cache に base_path そのものを保存する必要がなくなりました。
故にキャッシュからは同を取り除くようにいたしました。
