### ISSUE TITLE
peer のレプリケーションが ruby 1.9.2p290 で動作しない

### ISSUE THREAD

**Issue by tora** [suzumura-ss/castoro#60]
現象
peer が、レプリケーションしようとすると、通信がタイムアウトしてまい、レプリケーションが行われない。

環境
CentOS 5.6 64ビット
ruby-1.9.2-p290 をソースファイルからコンパイル、configure にオプションは無し
castoro-peer (0.2.0.pre)

情報収集
通信ポートへの接続確認
再起動直後は、
$ telnet localhost 30148
で、適当な文字を打ち込み、リターンキーを押すと、期待通り、以下のような応答がある。
["1.1","R",null,{"error":{"code":"Castoro::Peer::RetryableError","message":"server status: 10 10 offline for "}}]
しかしながら、レプリケーションしなくなっている状態では、応答がない。
このことから、プロセス内部でレプリケーション要求を処理するスレッドが無くなってしまう模様。

スレッド数の確認
$ ps -L -p crepdのプロセスID | wc
crepd の再起動直後は、ヘッダ行を含めて 47 行あるが、しばらくすると、減っていき、最終的に 27 行になってしまう。
このことから、プロセス内部でスレッドが異常終了している模様。

Exception の確認
crepd をデーモンプロセスとしてではなく、フォアグラウンドで実行、デバッグオプション付き
-f は、デーモンにならず、フォアグラウンドで実行
-d は、 Ruby の DEBUG を on にする。よって、内部の Exception を 表示してくれる。および、内部のデバッグ情報を表示する。
$ /usr/local/bin/crepd -f -d

```
Exception `Errno::EAGAIN' at /usr/local/lib/ruby/gems/1.9.1/gems/castoro-peer-0.2.0.pre/lib/castoro-peer/maintenace_server.rb:58 - Resource temporarily unavailable - read would block
```

が、延々と続くが、これについては、想定通り、問題は特になし

```
Exception `Castoro::Peer::RetryableError' at /usr/local/lib/ruby/gems/1.9.1/gems/castoro-peer-0.2.0.pre/lib/castoro-peer/crepd_receiver.rb:73 - server status: 10 10 offline for
```

は、crepd の動作モードが offline だったため。問題は特になし

```
Exception `SystemStackError' at /usr/local/lib/ruby/gems/1.9.1/gems/castoro-peer-0.2.0.pre/lib/castoro-peer/crepd_queue.rb - stack level too deep
Exception `SystemStackError' at /usr/local/lib/ruby/gems/1.9.1/gems/castoro-peer-0.2.0.pre/lib/castoro-peer/custom_condition_variable.rb:44 - stack level too deep
Exception `SystemStackError' at /usr/local/bin/crepd:19 - stack level too deep
```

/local/bin/crepd:19: stack level too deep (SystemStackError)

が、発生。どうやら、これが今回の問題の模様。

SystemStackError という例外が発生したため、rescue でキャッチできない。
そして、そのスレッドが強制終了されてしまう。

**Comment by tora** [comment]
解析結果

「Exception `SystemStackError' at ... crepd_queue.rb - stack level too deep」　は、以下のコードで発生。

https://github.com/ToshiyukiTerashita/castoro/blob/0.2/castoro-peer/lib/castoro-peer/crepd_queue.rb#L44

```
  def to_s
    inspect
  end
```

上記のコードで、ruby のバージョンによる振る舞いの違いが確認されました。
・ruby-1.9.1p376 では、問題は発生しない。
・ruby-1.9.2p290 では、今回の問題が発生する。

**Comment by tora** [comment]
ruby のソースコード内の object.c において、仕様変更がなされています。

1.9.1p376 - http://svn.ruby-lang.org/cgi-bin/viewvc.cgi/tags/v1_9_1_376/object.c?view=markup
1.9.2p290 - http://svn.ruby-lang.org/cgi-bin/viewvc.cgi/tags/v1_9_2_290/object.c?view=markup

rb_obj_inspect(VALUE obj) 関数です。 Object#inspect の実行で呼ばれるようです。

1.9.2 では、今回のインスタンスに #inspect を呼ぶと、以下の if 文で偽となり、結果的に #to_s が呼び出されるようになっているようです。

```
if (TYPE(obj) == T_OBJECT && rb_obj_basic_to_s_p(obj)) {
    ...
}
return rb_funcall(obj, rb_intern("to_s"), 0, 0);
```

そうなりますと、前出のコードは、

```
def to_s
    to_s   # 今回のようなインスタンスの場合、inspect は to_s を呼び出す。
end
```

となりまして、再帰的に無限に to_s が呼び出されることになり、その結果、ruby の VM 上でのスタックがオーバーフローしてしまい、SystemStackError 例外が発生する。

対策
・def to_s を削除する。さらに、
・"#{@foo}" による暗黙的な #to_s 呼び出しを止め、代わりに "#{@foo.inspect}" などと記述変更する。

**Comment by tora** [comment]
もう一つの例外
「Exception `SystemStackError' at ... custom_condition_variable.rb:44 - stack level too deep」 については、現時点で原因不明です。

ruby-1.9.2-p290.tar.bz を展開し、./configure すると、Makefile 内に gcc -O3 -ggdb ... というオプションが書き出されるようです。
CentOS 6.2 では、インストールメディアで gcc のバージョン 4.4.6 です。
gcc 4.4.x 系での -O3 による最適化オプションには問題がある。と言われているかと思います。
「gcc "-O3" ruby」　などで検索しますと、なにやら、見つかります。
また、ピアにおいては、gcc で最適化しても、「高速なアルゴリズム計算」などをしているわけではありません。むしろ、最適化による欠点であります、変数の格納方法や命令アドレスが変わってしまうため、コアダンプの解析が困難となってしまうことのほうが、問題となるのではないかと感じております。

開発側環境におきまして、CentOS 6.2 64ビット VMware上で プロセッサ数 2 という環境で、
(a) ./configure をいじらず、そのまま gcc -O3 -ggdb で、 ruby-1.9.2p290 をビルドし、 再現試験いたしましたところ、上述の #to_s は観察できず、一つ前のピアからレプリケーション要求を受け付けた時点で、crepd がクラッシュしてしまいました。

このような状況では、迷宮入りになりそうでしたので、
(b) configure ファイルにパッチを当てまして、 

```
: ${optflag=-O3}
```

という行を

```
: ${optflag=}
```

のように手修正し、ruby をビルドしなおし、インストールしてみましたところ、今度は、crepd の即クラッシュはなくなり、上述の #to_s 問題を解析できるようになりました。

**Comment by hamajyotan** [comment]
> 解析結果
> 
> 「Exception `SystemStackError' at ... crepd_queue.rb - stack level too deep」　は、以下のコードで発生。
> 
> https://github.com/ToshiyukiTerashita/castoro/blob/0.2/castoro-peer/lib/castoro-peer/crepd_queue.rb#L44
> 
> ```
>   def to_s
>     inspect
>   end
> ```
> 
> 上記のコードで、ruby のバージョンによる振る舞いの違いが確認されました。
> ・ruby-1.9.1p376 では、問題は発生しない。
> ・ruby-1.9.2p290 では、今回の問題が発生する。

#inspect は人にとって読みやすい、デバッグ向けのメソッドですので
- 文字列形成の一部に埋め込む
- 例外の description

等、ご利用の箇所での用途であれば #to_s を用いるべきですね。

**Comment by tora** [comment]
Ruby 側で、今回の 1.9.2 における仕様変更の是非について登録され、「まつもとゆきひろ」さん預かりになっている issue 

Overriding #to_s changes #inspect
http://bugs.ruby-lang.org/issues/4453

**Comment by tora** [comment]
ブランチ 0.2 上で、 castoro-peer-0.2.0.pre2　 2012-02-22  にて、対処いたしました。
#inspect, #to_s の是非については、別途検討とし、本 issue についてはクローズいたします。
