### ISSUE TITLE
crepd, cpeerd で、通常運転時も、デバッグ用文字列を評価している

### ISSUE THREAD

**Issue by tora** [suzumura-ss/castoro#62]
```
Log.debug "#{式}"
```

などとなっている箇所が、いくつかある。

```
Log.debug "#{式}" if $DEBUG
```

などと、すべきである。

**Comment by tora** [comment]
#60 の解析時に発見された。

**Comment by hamajyotan** [comment]
Log.debug メソッドの内部で
- $DEBUG が真ならば実行しない

とすべきかと思います。
かつ、 Log.debug にはブロックを渡して遅延評価させることで文字列を評価させないようにできます。

<pre>
module Log
  def self.debug message = nil
    return unless $DEBUG
    message = yield if block_given?
    put(message) if message
  end

  def self.put message
    # メッセージ出力実装
  end
end

def test_message message
  puts "#test_message called!"
  message
end

Log.debug { test_message("foo") } # $DEBUG が真の場合 #test_message は実行されない
</pre>

**Comment by tora** [comment]
ブランチ 0.2 上で、 castoro-peer-0.2.0.pre2　 2012-02-22 にて、対処いたしました。
「Log.debug にはブロックを渡して遅延評価」について、別途検討とし、本 issue については、クローズいたします。
