### ISSUE TITLE
ログレベルを Debug に設定すると undefined local variable or method エラーが発生する

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#65]
## 現象
- ログレベル DEBUG の場合に評価される。
  - https://github.com/ToshiyukiTerashita/castoro/blob/0.2/castoro-gateway/lib/castoro-gateway/cache_helper.rb#L53
  - base_path が不正

```
ERROR -- : undefined local variable or method `base_path' for #<Castoro::BasketCache:0x00000011cc0f90>
```

**Comment by hamajyotan** [comment]
base_path は INSERT コマンドに含まれるが、
BasketKey から格納パスの導出は BasketKeyConverter に委譲する事になったために不要。
故に base_path に関係する値は取り除く
