### ISSUE TITLE
指定した peer を含むキャッシュ情報を削除するコマンドを作成する

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#68]
### TODO
- 新規コマンド（purge）を追加する。
### コマンド内容

指定した peer を含む gateway のキャッシュから、peer 情報を削除する
- purge [peer名]
  - 例）　puege std101 下記のキャッシュ挙動になる
  - コマンド実行前：basket[1234.1.1] = { std101, std102, std103 } 
  - コマンド実行後：basket[1234.1.1] = { std102, std103 }

**Comment by hamajyotan** [comment]
作業
- castoro-common に新コマンドに対応したクラス追加
  - Castoro::Protocol::Command::Purge
  - Castoro::Protocol::Response::Purge
- gateway で purge コマンドを受けて以下の作業を行う
  - peer でフィルタした dump 結果を受信して basket の集合を得る
  - basket の集合と peer を引数に、該当キャッシュデータを削除するメソッドを定義
- castoro-gateway コマンドにサブコマンド "purge" を定義する
  - 上記挙動を実施する

**Comment by hamajyotan** [comment]
purge コマンド実行例

<pre>
$ castoro-gateway purge peer1 peer3
*** Purge Castoro::Gateway...
--- purge completed
      peer1 - 1000 baskets.
      peer3 - 1000 baskets.
*** done.
</pre>

**Comment by hamajyotan** [comment]
purge コマンドで対象キャッシュデータが存在しない場合

<pre>
$ castoro-gateway purge peer1 peer3
*** Purge Castoro::Gateway...
--- purge completed
      peer1 - 0 baskets.
      peer3 - 0 baskets.
*** done.
</pre>

**Comment by hamajyotan** [comment]
console 関係のリファクタ
- fork による dump 結果に PIPE を用いで UNIX ソケット通信をやめた
- STATUS, DUMP, PURGE request/response を排除 - druby 通信に
  - 0.2.0 では 1.9.2 以上
  - 1.9.2 での druby 動作安定を確認
