### ISSUE TITLE
GET 時、キャッシュに Peer 3台が揃っていない場合キャッシュを成長させる。

### ISSUE THREAD

**Issue by lamatsujun** [suzumura-ss/castoro#69]
### TODO
- GET 時に現状のキャッシュ内容で返答後、後段の Peer に GET をマルチキャストする。
### 前提条件
- キャッシュに Peer が3台揃っていない。
- キャッシュされている Peer が全て正常状態の場合

**Comment by hamajyotan** [comment]
新しいコンフィグ値 "cache / replication_count"
- original と island 専用の値
- 既定値: 3
- キャッシュの保存している peer 数が、この値に満たない場合、かつキャッシュ済み peer が全て ACTIVE の場合 peer にマルチキャストする

**Comment by hamajyotan** [comment]
実装済み

残作業
- 本挙動に合わせた spec 記述
- 新しい config 値 "replication_count" の説明を wiki 化

**Comment by lamatsujun** [comment]
## wiki 化
- wiki 下記ページに内容を記載
  - [Castoro::Gateway castoro-0.2](https://github.com/ToshiyukiTerashita/castoro/wiki/Castoro%3A%3Agateway-castoro-0.2)
