### ISSUE TITLE
kc ベースの castoro-gateway キャッシュプラグインを C++ で構築する

### ISSUE THREAD

**Issue by hamajyotan** [suzumura-ss/castoro#70]
- gem kyotocabinet-ruby を用いずに直接 C++ の API を叩くキャッシュを作成する
  - 作成は完了 @fe767dce6f7b941896e183a69755b67db5a2acc6
- 性能検証

**Comment by hamajyotan** [comment]
挿入削除検証用スクリプト

<pre>
#!/usr/bin/env ruby

require 'rubygems'
require 'castoro-gateway-kyotocabinet'

include Castoro

size   = 1024*1024*1024
counts = [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000, 500000, 1000000, 2000000, 5000000]
peers  = ["std100", "std101", "std102"]

def classname_pretty klass
  klass == Castoro::Cache ? "original" : "kcabinet"
end

[Cache, Cache::KyotoCabinet].each { |klass|
  counts.each { |count|
    GC.start
    klass.new(size).tap { |cache|
      stime = Time.now
      peers.each { |p|
        count.times { |i| cache.insert_element p, i, 1, 1 }
      }
      etime = Time.now
      puts("[%s] %08d insert: %.3f sec." % [classname_pretty(klass), count, (etime - stime)])
      GC.start
      stime = Time.now
      peers.each { |p|
        count.times { |i| cache.erase_element p, i, 1, 1 }
      }
      etime = Time.now
      puts("[%s] %08d delete: %.3f sec." % [classname_pretty(klass), count, (etime - stime)])
    }
    GC.start
  }
}
</pre>

**Comment by hamajyotan** [comment]
挿入削除測定結果

およそ 3倍強の性能差が出ている

<table>
<thead>
<th>insert</th><th>original</th><th>kc</th>
</thead>
<tbody>
<tr><td>100</td><td>0.003</td><td>0.001</td></tr>
<tr><td>200</td><td>0.005</td><td>0.003</td></tr>
<tr><td>500</td><td>0.011</td><td>0.006</td></tr>
<tr><td>1000</td><td>0.023</td><td>0.011</td></tr>
<tr><td>2000</td><td>0.051</td><td>0.019</td></tr>
<tr><td>5000</td><td>0.125</td><td>0.04</td></tr>
<tr><td>10000</td><td>0.257</td><td>0.074</td></tr>
<tr><td>20000</td><td>0.526</td><td>0.142</td></tr>
<tr><td>50000</td><td>1.355</td><td>0.345</td></tr>
<tr><td>100000</td><td>2.742</td><td>0.684</td></tr>
<tr><td>200000</td><td>5.564</td><td>1.365</td></tr>
<tr><td>500000</td><td>14.01</td><td>3.452</td></tr>
<tr><td>1000000</td><td>28.792</td><td>7.051</td></tr>
<tr><td>2000000</td><td>56.804</td><td>14.533</td></tr>
<tr><td>5000000</td><td>144.756</td><td>39.172</td></tr>
</tbody>
</table>


<table>
<thead>
<th>delete</th><th>original</th><th>kc</th>
</thead>
<tbody>
<tr><td>100</td><td>0.002</td><td>0.001</td></tr>
<tr><td>200</td><td>0.005</td><td>0.001</td></tr>
<tr><td>500</td><td>0.011</td><td>0.003</td></tr>
<tr><td>1000</td><td>0.023</td><td>0.007</td></tr>
<tr><td>2000</td><td>0.052</td><td>0.013</td></tr>
<tr><td>5000</td><td>0.126</td><td>0.033</td></tr>
<tr><td>10000</td><td>0.263</td><td>0.065</td></tr>
<tr><td>20000</td><td>0.541</td><td>0.131</td></tr>
<tr><td>50000</td><td>1.372</td><td>0.327</td></tr>
<tr><td>100000</td><td>2.756</td><td>0.653</td></tr>
<tr><td>200000</td><td>5.55</td><td>1.314</td></tr>
<tr><td>500000</td><td>14.004</td><td>3.331</td></tr>
<tr><td>1000000</td><td>28.192</td><td>6.823</td></tr>
<tr><td>2000000</td><td>56.565</td><td>14.129</td></tr>
<tr><td>5000000</td><td>145.365</td><td>38.123</td></tr>
</tbody>
</table>

**Comment by hamajyotan** [comment]
検証内容残
- 取得時の性能測定
- basket あたりのメモリ使用量測定

**Comment by hamajyotan** [comment]
CentOS 5.x 系でのインストール方法を README.textile に追記
- yum install gcc44 gcc44-c++
- ソースコード展開
  - CC=gcc44 CXX=g++44 ./configure && make && sudo make install
- /usr/local/lib をライブラリパスに含める
- CC=gcc44 CXX=g++44 gem install castoro-gateway-kyotocabinet-0.2.0.pre.gem

**Comment by hamajyotan** [comment]
参照測定結果

およそ 2.5倍の性能差が出ている

<table>
<thead>
<th>get</th><th>original</th><th>kc</th>
</thead>
<tbody>
<tr><td>100</td><td>0.002</td><td>0.001</td></tr>
<tr><td>200</td><td>0.003</td><td>0.002</td></tr>
<tr><td>500</td><td>0.017</td><td>0.003</td></tr>
<tr><td>1000</td><td>0.015</td><td>0.006</td></tr>
<tr><td>2000</td><td>0.031</td><td>0.013</td></tr>
<tr><td>5000</td><td>0.078</td><td>0.031</td></tr>
<tr><td>10000</td><td>0.154</td><td>0.063</td></tr>
<tr><td>20000</td><td>0.311</td><td>0.126</td></tr>
<tr><td>50000</td><td>0.779</td><td>0.318</td></tr>
<tr><td>100000</td><td>1.57</td><td>0.635</td></tr>
<tr><td>200000</td><td>3.148</td><td>1.276</td></tr>
<tr><td>500000</td><td>8.056</td><td>3.335</td></tr>
<tr><td>1000000</td><td>16.281</td><td>6.467</td></tr>
<tr><td>2000000</td><td>32.486</td><td>13.147</td></tr>
<tr><td>5000000</td><td>81.819</td><td>33.841</td></tr>
</tbody>
</table>

**Comment by tora** [comment]
キャッシュなし（固定値を単純に返すなど）についても測定してみると、総合性能に加えて、キャッシュ寄与分での性能も算出可能かと思いました。

**Comment by hamajyotan** [comment]
#### 結論
- メモリ空間効率は、オリジナルの 1/10 (10倍のメモリを要する)
- 参照, 追加, 削除 の速度はおよそ3倍弱

#### オリジナルと KC での違い
- キーがシーケンシャルに増加する場合はオリジナル
- キーがランダムにアクセスされる場合は KC
- メモリ使用量はオリジナルが優れる
- 速度は KC が優れる
