### ISSUE TITLE
gateway, peer でのコンフィグで用いられるキー名を統一する

### ISSUE THREAD

**Issue by hamajyotan** [suzumura-ss/castoro#73]
例

<table>
<thead>
<tr><th>Peer</th><th>Gateway</th></tr>
</thead>
<tbody>
<tr><td>GatewayUDPCommandPort</td><td>gateway_multicast_port</td></tr>
<tr><td>PeerUDPCommandPort</td><td>peer_multicast_port</td></tr>
</tbody>
</table>

微妙に差がある名称を統一する。

**Comment by hamajyotan** [comment]
### 定義案

#### 4つの要素をアンダースコアで結合した名称とする
1. 受信の主体
2. 用途
3. TCP/UDP(unitcast|multicast|broadcast)
4. port|addr|device

##### 受信の主体
- peer -> peer 専用
- gateway -> gateway 専用, master+island 共用
- master -> master 専用
- island -> island 専用
- storage -> peer+gateway 共用

<table>
<tr><td colspan="3">storage</td></tr>
<tr><td rowspan="2">peer</td><td colspan="2">gateway</td></tr>
<tr><td>master</td><td>island</td></tr>
</table>


##### 用途
- その用途を表す一単語

##### TCP/UDP
- TCP の場合は省略
- UDP の場合以下のいずれか
  - unicast
  - multicast
  - broadcast

##### port | addr | device
- 以下のいずれか
  - port
  - addr
  - device

**Comment by hamajyotan** [comment]
### 上記定義案の具体例

<table>
<thead>
<tr><th>現状のGateway設定名</th><th>例</th></tr>
</thead>
<tbody>
<tr><td>gateway_unicast_port</td><td>gateway_communication_unicast_port</td></tr>
<tr><td>gateway_console_port</td><td>gateway_console_port</td></tr>
<tr><td>gateway_multicast_port</td><td>gateway_learning_multicast_port</td></tr>
<tr><td>gateway_watchdog_port</td><td>gateway_watchdog_multicast_port</td></tr>
<tr><td>peer_multicast_addr</td><td>storage_communication_multicast_addr</td></tr>
<tr><td>peer_multicast_device</td><td>storage_communication_multicast_device</td></tr>
<tr><td>peer_multicast_port</td><td>peer_communication_multicast_port</td></tr>
<tr><td>master_multicast_addr</td><td>master_communication_multicast_addr</td></tr>
<tr><td>island_broadcast_port</td><td>island_communication_broadcast_port</td></tr>
<tr><td>island_multicast_addr</td><td>island_communication_multicast_addr</td></tr>
<tr><td>island_multicast_device</td><td>island_communication_multicast_device</td></tr>
</tbody>
</table>

**Comment by hamajyotan** [comment]
##### communication は長いか ?

c11n とか

**Comment by hamajyotan** [comment]
##### c11n は Serialization の事らしい

混乱を招くので却下

**Comment by lamatsujun** [comment]
#### 項目名を下記で統一
- ソースコード
- wiki ページ

<table>
<thead>
<tr><th>現状のGateway設定名</th><th>変更後</th></tr>
</thead>
<tbody>
<tr><td>gateway_unicast_port</td><td>gateway_comm_udpport</td></tr>
<tr><td>gateway_console_port</td><td>gateway_console_tcpport</td></tr>
<tr><td>gateway_multicast_port</td><td>gateway_learning_udpport_multicast</td></tr>
<tr><td>gateway_watchdog_port</td><td>gateway_watchdog_udpport_multicast</td></tr>
<tr><td>peer_multicast_addr</td><td>gateway_comm_ipaddr_multicast</td></tr>
<tr><td>peer_multicast_device</td><td>gateway_comm_device_multicast</td></tr>
<tr><td>peer_multicast_port</td><td>peer_comm_udpport_multicast</td></tr>
<tr><td>master_multicast_addr</td><td>master_comm_ipaddr_multicast</td></tr>
<tr><td>island_broadcast_port</td><td>island_comm_udpport_broadcast</td></tr>
<tr><td>island_multicast_addr</td><td>island_comm_ipaddr_multicast</td></tr>
<tr><td>island_multicast_device</td><td>island_comm_device_multicast</td></tr>
<tr><td>base_dir</td><td>basket_basedir</td></tr>
<tr><td>converter</td><td>basket_keyconverter</td></tr>
</tbody>
</table>

**Comment by lamatsujun** [comment]
wiki ページ対応完了
- [Castoro::Gateway キャッシュ plug-in 仕様](https://github.com/ToshiyukiTerashita/castoro/wiki/Castoro::cache-plugin-specifications)
- [Castoro::Gateway castoro-0.2](https://github.com/ToshiyukiTerashita/castoro/wiki/Castoro::gateway-castoro-0.2)

**Comment by hamajyotan** [comment]
0.2.0 リリースに伴いクローズ
- [Castoro::Gateway キャッシュ plug-in 仕様](https://github.com/ToshiyukiTerashita/castoro/wiki/Castoro::cache-plugin-specifications)
- [Castoro::Gateway castoro-0.2](https://github.com/ToshiyukiTerashita/castoro/wiki/Castoro::gateway-castoro-0.2)
