### ISSUE TITLE
FINALIZE時にファイルに実行権限(+x)が付与される

### ISSUE THREAD

**Issue by suzumura-ss** [suzumura-ss/castoro#8]
FINALIZE後のbasketの中のファイルが r-xr-xr-x になっているものがあります。

**Comment by hamajyotan** [comment]
実際のファイル操作を担うプログラム Castoro::Manipulator に問題があった。

Manipulator は Peer から「特定のパーミッションでディレクトリを作成せよ」という旨の
パケットを受信するが、これはディレクトリに対するパーミッションであり
ファイルにそれを適用すべきではなかった。

正しくは、ファイルに適用すべきパーミッションは
「ディレクトリに適用するパーミッションから、実行権限をマスクしたもの」
を適用すべきである。

Castoro-Manipulator 0.0.7 で本問題は解決済み
